### ISSUE TITLE
Error in "import myfitnesspal"

### ISSUE THREAD

**Issue by jykim** [coddingtonbear/python-myfitnesspal#10]
Hi, 

I can't seem to import the library in my Ubuntu.

Any idea?

```
$ uname -a
Linux jink 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 15:31:16 UTC 2013 i686 i686 i386 GNU/Linux

$ python -i
Python 2.7.3 (default, Feb 27 2014, 20:00:17)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import myfitnesspal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/__init__.py", line 1, in <module>
    from myfitnesspal.client import Client
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/client.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/lib/python2.7/dist-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 12, in <module>
    from .util import resolve_cert_reqs, resolve_ssl_version, assert_fingerprint
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/__init__.py", line 18, in <module>
    from .timeout import (
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/timeout.py", line 4, in <module>
    from ..exceptions import TimeoutStateError
ImportError: cannot import name TimeoutStateError
>>>
```

**Comment by coddingtonbear** [comment]
I'm afraid I can't really tell what might be the problem in your above traceback, but given that [the tests are passing](https://travis-ci.org/coddingtonbear/python-myfitnesspal/builds/38899605), I *bet* it's an incompatibility between the version of `urllib3` and `requests` that you have installed as system packages.

I really recommend using [`virtualenv`](http://docs.python-guide.org/en/latest/dev/virtualenvs/) with any python project (including this one) to make sure the packages installed as requirements for any given library are kept independent from other packages you might have installed on your system -- whether or not installing two libraries side-by side in system packages will conflict with one another it's really dependent upon how lucky you are, and it's best to keep things separated when possible.

Could you give it a shot after installing this in a clean virtualenv?

**Comment by coddingtonbear** [comment]
Hey there @jykim; I'm closing this since you haven't replied recently; let me know if you're still having trouble, though.

Cheers!
