### ISSUE TITLE
IndexError in _get_goals

### ISSUE THREAD

**Issue by bradgarropy** [coddingtonbear/python-myfitnesspal#12]
Hello @coddingtonbear,
I believe I found an issue when running _get_goals. I've copied my use case below, and substituted fake values for the username and password.

```
$ python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import myfitnesspal
>>> client = myfitnesspal.Client("username", "password")
>>> day = client.get_date(2015, 4, 20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Python27\lib\site-packages\myfitnesspal\client.py", line 209, in get_date
    goals = self._get_goals(document)
  File "d:\Python27\lib\site-packages\myfitnesspal\client.py", line 109, in _get_goals
    total_header = document.xpath("//tr[@class='total']")[0]
IndexError: list index out of range
```

I double checked the **Food Diary** for the given date (4/20/2105) and the source HTML does indeed have the *total* class defined just like your test cases.

```html
<tr class="total">

    <td class="first">Totals</td>
        <td>1,297</td>
        <td>157</td>
        <td>39</td>
        <td>86</td>
        <td>20</td>
        <td>1,307</td>
    <td class="empty"></td>

</tr>
```

I will be glad to follow up with further information, or submit a potential fix for the issue myself :smiley:

Looking forward to your response!

@bradgarropy

**Comment by bradgarropy** [comment]
After further investigation, I found that the URL created by `_get_url_for_date` was incorrect. Because the method uses `os.path.join`, which inserts file path separators based on `os.sep`, this caused a back slash to be placed in the URL instead of a forward slash on my Windows machine.

See the execution example below. *Note that I've placed a fake username and password after pasting the code here.*

```
>>> from myfitnesspal import client
>>> myclient=client.Client("username", "password")
>>> day=myclient.get_date(2015,4,20)
url: http://www.myfitnesspal.com/food/diary\username?date=2015-04-20
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "myfitnesspal\client.py", line 211, in get_date
    goals = self._get_goals(document)
  File "myfitnesspal\client.py", line 109, in _get_goals
    total_header = document.xpath("//tr[@class='total']")[0]
IndexError: list index out of range
```

**Comment by bradgarropy** [comment]
Although the true fix for the issue should remove using `os.path.join` altogether, I've made a slight fix with a smaller code impact that still gets the job done.

```python
def _get_url_for_date(self, date, username):
        return os.path.join(
            self.BASE_URL,
            'food/diary/',
            username
        ) + '?date=%s' % (
            date.strftime('%Y-%m-%d')
        )
```

The `BASE_URL` already contains a backslash at the end. I added a backslash after **food/diary** and removed the comma after username. This creates a valid URL like the one below as it forces `os.path.join` to use forward slashes instead of substituting the separators itself.

```
>>> from myfitnesspal import client
>>> myclient=client.Client("username", "username")
>>> day=myclient.get_date(2015,4,20)
url: http://www.myfitnesspal.com/food/diary/username?date=2015-04-20
>>> day
<04/20/15 {'fiber': 28, 'sodium': 2234, 'carbohydrates': 247, 'calories': 2124, 'fat': 45, 'protein': 189}>
```

I'll submit a **Pull Request** with my code changes! Hope you approve!

@bradgarropy
