### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by chazzaspazz** [coddingtonbear/python-myfitnesspal#127]
Hi, having the following issue when trying to install:

 ERROR: Command errored out with exit status 1:
   command: /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"'; __file__='"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-wheel-gjctmsns
       cwd: /private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/
  Complete output (29 lines):
  /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py", line 4, in <module>
      setup(use_scm_version=True)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 771, in resolve
      dist = best[req.key] = env.best_match(
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/.eggs/MarkupSafe-2.0.1-py3.10-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed building wheel for measurement
  Running setup.py clean for measurement
  ERROR: Command errored out with exit status 1:
   command: /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"'; __file__='"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8
  Complete output (29 lines):
  /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py", line 4, in <module>
      setup(use_scm_version=True)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 771, in resolve
      dist = best[req.key] = env.best_match(
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/.eggs/MarkupSafe-2.0.1-py3.10-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed cleaning build dir for measurement
Successfully built lxml
Failed to build measurement
Installing collected packages: mpmath, wcwidth, urllib3, typing-extensions, sympy, six, pygments, idna, commonmark, colorama, charset-normalizer, certifi, rich, requests, python-dateutil, measurement, lxml, keyring, blessed, myfitnesspal
    Running setup.py install for measurement ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"'; __file__='"'"'/private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-record-8rczmmai/install-record.txt --single-version-externally-managed --compile --install-headers /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/include/site/python3.10/measurement
         cwd: /private/var/folders/lv/rhp_1k_57jbb93rvwgtbl7600000gn/T/pip-install-1ajy2h46/measurement_b1e3b8da71824d899b619776d8c1edb8/
    Complete output (29 lines):
    /Users/charliebutcher/Desktop/PycharmProj/MFP/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      warnings.warn(

**Comment by hannahburkhardt** [comment]
I'm also getting an error when using python 3.10. For now, try using python 3.7 instead.

**Comment by Nimrais** [comment]
Hmm, I am using python 3.10.2 all are working.
For installation, I am using poetry.

```
myfitnesspal 1.16.6 Access health and fitness data stored in Myfitnesspal
├── blessed >=1.8.5,<2.0
│   ├── jinxed >=1.1.0 
│   │   └── ansicon * 
│   ├── six >=1.9.0 
│   └── wcwidth >=0.1.4 
├── keyring >=8.0,<22.0
│   ├── jeepney >=0.4.2 
│   ├── pywin32-ctypes <0.1.0 || >0.1.0,<0.1.1 || >0.1.1 
│   └── secretstorage >=3.2 
│       ├── cryptography >=2.0 
│       │   └── cffi >=1.12 
│       │       └── pycparser * 
│       └── jeepney >=0.6 (circular dependency aborted here)
├── lxml >=4.2.5,<5
├── measurement >=3.2.0,<4.0
│   └── sympy >=0.7.3 
│       └── mpmath >=0.19 
├── python-dateutil >=2.4,<3
│   └── six >=1.5 
├── requests >=2.17.0,<3
│   ├── certifi >=2017.4.17 
│   ├── charset-normalizer >=2.0.0,<2.1.0 
│   ├── idna >=2.5,<4 
│   └── urllib3 >=1.21.1,<1.27 
└── rich >=9.10.0,<10
    ├── colorama >=0.4.0,<0.5.0 
    ├── commonmark >=0.9.0,<0.10.0 
    ├── pygments >=2.6.0,<3.0.0 
    └── typing-extensions >=3.7.4,<4.0.0 
```

**Comment by hannahburkhardt** [comment]
I seem to get the same issue with poetry! I believe it's the fact that measurement v3.2.0 does not seem to work with python 3.10.

**Comment by qwarkys** [comment]
For some reason I was able to install mfp (including measurement 3.2.) on python 3.10.5.  It would not install on 3.11b3, but I was able to get it going by copying the relevant directories from 3.10.

**Comment by xtechgamer735** [comment]
@qwarkys would you by any chance be able to give a little more detail on how you fixed it? I just can't get it to work on 3.10.5. Thanks a lot!
