### ISSUE TITLE
Unpacking Values after 2.0.0 Update:

### ISSUE THREAD

**Issue by chazzaspazz** [coddingtonbear/python-myfitnesspal#145]
Hi Guys,

Apologies if this is a simple fix or stupid question, but after the recent update, when using cookie jar I am getting the following Error:

`Traceback (most recent call last):
  File "/Users/charliebutcher/Library/Mobile Documents/com~apple~CloudDocs/100_Days_of_Python/MFP/main.py", line 1, in <module>
    from sheety import SheetUpdate
  File "/Users/charliebutcher/Library/Mobile Documents/com~apple~CloudDocs/100_Days_of_Python/MFP/sheety.py", line 2, in <module>
    from data_manager import DataManager
  File "/Users/charliebutcher/Library/Mobile Documents/com~apple~CloudDocs/100_Days_of_Python/MFP/data_manager.py", line 7, in <module>
    client = myfitnesspal.Client(MFP_Name, MFP_PW)
  File "/Users/charliebutcher/Library/Mobile Documents/com~apple~CloudDocs/100_Days_of_Python/MFP/venv/lib/python3.10/site-packages/myfitnesspal/client.py", line 76, in __init__
    self.session.cookies.update(cookiejar)
  File "/Users/charliebutcher/Library/Mobile Documents/com~apple~CloudDocs/100_Days_of_Python/MFP/venv/lib/python3.10/site-packages/requests-2.26.0-py3.10.egg/requests/cookies.py", line 354, in update
    super(RequestsCookieJar, self).update(other)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_collections_abc.py", line 996, in update
    for key, value in other:
ValueError: not enough values to unpack (expected 2, got 1)`

Any idea on what I might be able to do to fix this?

Thanks!

**Comment by ColorfulQuark** [comment]
I'm also getting ValueError:

`  File "C:\temp\progs\m3.py", line 14, in login`
`    client = myfitnesspal.Client("xxxxxx", "yyyyyy")`
`  File "C:\program files\python310\lib\site-packages\myfitnesspal\client.py", line 76, in __init__`
`    self.session.cookies.update(cookiejar)`
`  File "C:\program files\python310\lib\site-packages\requests\cookies.py", line 354, in update`
`    super(RequestsCookieJar, self).update(other)`
`  File "C:\program files\python310\lib\_collections_abc.py", line 999, in update`
`    for key, value in other:`
`ValueError: not enough values to unpack (expected 2, got 1)``

**Comment by coddingtonbear** [comment]
I've just posted a doc that outlines the upgrade path between the 1.x and 2.x versions; have a look at https://python-myfitnesspal.readthedocs.io/en/latest/upgrading.html.
