### ISSUE TITLE
get_date not working

### ISSUE THREAD

**Issue by adamjermyn** [coddingtonbear/python-myfitnesspal#23]
Currently get_date errors out with the following message:
 
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    day = client.get_date(today)
  File "/usr/local/lib/python2.7/site-packages/myfitnesspal/client.py", line 222, in get_date
    goals = self._get_goals(document)
  File "/usr/local/lib/python2.7/site-packages/myfitnesspal/client.py", line 122, in _get_goals
    total_header = document.xpath("//tr[@class='total']")[0]
IndexError: list index out of range

This happens regardless of the date requested.

**Comment by mikeres0** [comment]
For the username are you typing in your email address? Try typing in your actual username, this cured the error for me.

**Comment by adamjermyn** [comment]
Ah that works, thanks!

-Adam

**Comment by mikeres0** [comment]
You're welcome!
