### ISSUE TITLE
Changed page?

### ISSUE THREAD

**Issue by edusteinhorst** [coddingtonbear/python-myfitnesspal#39]
Been getting this lately. Command is myfitnesspal day $username:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/cmdline.py", line 46, in main
    COMMANDS[args.command[0]]['function'](args, *extra)
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/commands.py", line 117, in day
    day = client.get_date(args.date)
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/client.py", line 329, in get_date
    meals = self._get_meals(document)
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/client.py", line 285, in _get_meals
    value = self._get_numeric(column.text)
  File "/usr/local/lib/python2.7/dist-packages/myfitnesspal/client.py", line 215, in _get_numeric
    return int(re.sub(r'[^\d.]+', '', string))
ValueError: invalid literal for int() with base 10: ''

**Comment by edusteinhorst** [comment]
Sorry, this is fixed by pr #36
