### ISSUE TITLE
SyntaxError: invalid syntax when attempting to install from scratch

### ISSUE THREAD

**Issue by Imisrael** [coddingtonbear/python-myfitnesspal#94]
Whether I try to install with both pip or the setup.py script, I get the same error: 

```
  File "/tmp/easy_install-DSq1Na/measurement-3.2.0/temp/easy_install-9xIGDB/Sphinx-2.4.3/sphinx/deprecation.py", line 29
    def deprecated_alias(modname: str, objects: Dict, warning: Type[Warning]) -> None:
```

Here's the full dump: 

```running install
running bdist_egg
running egg_info
creating myfitnesspal.egg-info
writing requirements to myfitnesspal.egg-info/requires.txt
writing myfitnesspal.egg-info/PKG-INFO
writing top-level names to myfitnesspal.egg-info/top_level.txt
writing dependency_links to myfitnesspal.egg-info/dependency_links.txt
writing entry points to myfitnesspal.egg-info/entry_points.txt
writing manifest file 'myfitnesspal.egg-info/SOURCES.txt'
reading manifest file 'myfitnesspal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'readme.rst'
writing manifest file 'myfitnesspal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/keyring_utils.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/entry.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/client.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/fooditem.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/note.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/exercise.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/cmdline.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/day.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/commands.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/base.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/meal.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/__init__.py -> build/lib.linux-x86_64-2.7/myfitnesspal
copying myfitnesspal/fooditemserving.py -> build/lib.linux-x86_64-2.7/myfitnesspal
creating build/lib.linux-x86_64-2.7/tests
copying tests/test_client.py -> build/lib.linux-x86_64-2.7/tests
copying tests/base.py -> build/lib.linux-x86_64-2.7/tests
copying tests/__init__.py -> build/lib.linux-x86_64-2.7/tests
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/keyring_utils.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/entry.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/client.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/fooditem.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/note.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/exercise.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/cmdline.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/day.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/commands.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/base.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/meal.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/__init__.py -> build/bdist.linux-x86_64/egg/myfitnesspal
copying build/lib.linux-x86_64-2.7/myfitnesspal/fooditemserving.py -> build/bdist.linux-x86_64/egg/myfitnesspal
creating build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/test_client.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/base.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/keyring_utils.py to keyring_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/entry.py to entry.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/client.py to client.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/fooditem.py to fooditem.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/note.py to note.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/exercise.py to exercise.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/cmdline.py to cmdline.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/day.py to day.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/commands.py to commands.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/base.py to base.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/meal.py to meal.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/myfitnesspal/fooditemserving.py to fooditemserving.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_client.py to test_client.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/base.py to base.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying myfitnesspal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
tests.base: module references __file__
creating dist
creating 'dist/myfitnesspal-1.13.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing myfitnesspal-1.13.4-py2.7.egg
removing '/home/plex/.local/lib/python2.7/site-packages/myfitnesspal-1.13.4-py2.7.egg' (and everything under it)
creating /home/plex/.local/lib/python2.7/site-packages/myfitnesspal-1.13.4-py2.7.egg
Extracting myfitnesspal-1.13.4-py2.7.egg to /home/plex/.local/lib/python2.7/site-packages
myfitnesspal 1.13.4 is already the active version in easy-install.pth
Installing myfitnesspal script to /home/plex/.local/bin

Installed /home/plex/.local/lib/python2.7/site-packages/myfitnesspal-1.13.4-py2.7.egg
Processing dependencies for myfitnesspal==1.13.4
Searching for measurement>=1.5
Reading https://pypi.python.org/simple/measurement/
Downloading https://files.pythonhosted.org/packages/31/fe/c7fee7e60f30bc3853662452b063aa118ca87b68e77897907c2d5f8b31da/measurement-3.2.0.tar.gz#sha256=352b20f7f0e553236af7c5ed48d091a51cf26061c1a063f46b31706ff7c0d57a
Best match: measurement 3.2.0
Processing measurement-3.2.0.tar.gz
Writing /tmp/easy_install-DSq1Na/measurement-3.2.0/setup.cfg
Running measurement-3.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DSq1Na/measurement-3.2.0/egg-dist-tmp-pW_CXP
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    'myfitnesspal = myfitnesspal.cmdline:main'
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-DSq1Na/measurement-3.2.0/setup.py", line 4, in <module>
    
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-DSq1Na/measurement-3.2.0/temp/easy_install-9xIGDB/Sphinx-2.4.3/setup.py", line 8, in <module>
    
  File "/tmp/easy_install-DSq1Na/measurement-3.2.0/temp/easy_install-9xIGDB/Sphinx-2.4.3/sphinx/__init__.py", line 20, in <module>
  File "/tmp/easy_install-DSq1Na/measurement-3.2.0/temp/easy_install-9xIGDB/Sphinx-2.4.3/sphinx/deprecation.py", line 29
    def deprecated_alias(modname: str, objects: Dict, warning: Type[Warning]) -> None:
                                ^
SyntaxError: invalid syntax```

**Comment by Imisrael** [comment]
Never mind. This needed Python 3.6 or higher
